-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
--
-- vim.api.nvim_create_autocmd("BufWritePre", {
--   pattern = "*.ts*",
--   command = ":TSToolsRemoveUnusedImports sync",
-- })

-- vim.api.nvim_create_autocmd({ "BufEnter" }, {
--   pattern = { "*.py", "*.lua" },
--   callback = require("zen-mode").open,
-- })
--
-- vim.api.nvim_create_autocmd({ "BufLeave" }, {
--   pattern = { "*.py", "*.lua" },
--   callback = require("zen-mode").close,
-- })
